part of '../core_suggestion_area.dart';

/// The mode of suggestions displayed in the suggestion area.
enum SuggestionMode {
  /// Suggestions generated by AI.
  ai,

  /// Suggestions for unit conversion.
  conversion,
}

/// Data representation for a single suggestion chip.
class SuggestionData {
  /// The display label of the suggestion chip.
  final String label;

  /// The raw value associated with the suggestion.
  final String value;

  /// The optional measurement unit for the suggestion.
  final String? unit;

  /// The callback invoked when the suggestion chip is tapped.
  final VoidCallback onTap;

  /// Creates a [SuggestionData] instance.
  SuggestionData({
    required this.label,
    required this.value,
    this.unit,
    required this.onTap,
  });
}

class _SuggestionList extends StatefulWidget {
  final List<SuggestionData>? suggestions;

  const _SuggestionList({
    super.key,
    this.suggestions,
  });

  @override
  State<_SuggestionList> createState() => _SuggestionListState();
}

class _SuggestionListState extends State<_SuggestionList> {
  late List<ValueNotifier<bool>> _notifiers;

  @override
  void initState() {
    super.initState();
    _initNotifiers();
  }

  @override
  void didUpdateWidget(_SuggestionList oldWidget) {
    super.didUpdateWidget(oldWidget);
    if (widget.suggestions != oldWidget.suggestions) {
      _disposeNotifiers();
      _initNotifiers();
    }
  }

  void _initNotifiers() {
    _notifiers = widget.suggestions?.map((_) => ValueNotifier(false)).toList() ?? [];
  }

  void _disposeNotifiers() {
    for (var notifier in _notifiers) {
      notifier.dispose();
    }
  }

  @override
  void dispose() {
    _disposeNotifiers();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final suggestions = widget.suggestions;
    if (suggestions == null || suggestions.isEmpty) {
      return const SizedBox.shrink();
    }

    return Align(
      alignment: AlignmentDirectional.centerStart,
      child: Wrap(
        spacing: CoreSpacing.space2,
        alignment: WrapAlignment.start,
        children: List.generate(suggestions.length, (index) {
          final data = suggestions[index];
          return CoreChip(
            label: data.label,
            value: data.value,
            unit: data.unit,
            selected: _notifiers[index],
            onTap: data.onTap,
            isSmartChip: true,
            size: CoreChipSize.large,
          );
        }),
      ),
    );
  }
}
